In [1]:
import numpy as np
import pandas as pd
from fast_ml.model_development import train_valid_test_split
from sklearn.model_selection import KFold
from sklearn.metrics import root_mean_squared_error

In [2]:
df= pd.read_csv('dataset/dataset', sep=';')

In [3]:
df

,heure,year,month,day,Frequentation,isWeekday,isHoliday,season,RR1,QRR1,...,NEIGETOT,QNEIGETOT,GLO,QGLO,GLO2,QGLO2,INS,QINS,INS2,QINS2
0,00:00,2022,1,1,1469,False,True,winter,0.0,1.0,...,NaN,NaN,0.0,9.0,0.0,9.0,0.0,9.0,0.0,9.0
1,01:00,2022,1,1,910,False,True,winter,0.0,1.0,...,NaN,NaN,0.0,9.0,0.0,9.0,0.0,9.0,0.0,9.0
2,02:00,2022,1,1,535,False,True,winter,0.0,1.0,...,0.0,9.0,0.0,9.0,0.0,9.0,0.0,9.0,0.0,9.0
3,03:00,2022,1,1,200,False,True,winter,0.0,1.0,...,0.0,9.0,0.0,9.0,0.0,9.0,0.0,9.0,0.0,9.0
4,04:00,2022,1,1,406,False,True,winter,0.0,1.0,...,0.0,9.0,0.0,9.0,0.0,9.0,0.0,9.0,0.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18303,19:00,2024,9,30,6291,True,False,autumn,0.0,1.0,...,0.0,9.0,0.0,9.0,0.0,9.0,0.0,9.0,0.0,9.0
18304,20:00,2024,9,30,7431,True,False,autumn,0.0,1.0,...,0.0,9.0,0.0,9.0,0.0,9.0,0.0,9.0,0.0,9.0
18305,21:00,2024,9,30,2081,True,False,autumn,0.0,1.0,...,0.0,9.0,0.0,9.0,0.0,9.0,0.0,9.0,0.0,9.0
18306,22:00,2024,9,30,2318,True,False,autumn,0.0,1.0,...,0.0,9.0,0.0,9.0,0.0,9.0,0.0,9.0,0.0,9.0
18307,23:00,2024,9,30,876,True,False,autumn,0.0,1.0,...,0.0,9.0,0.0,9.0,0.0,9.0,0.0,9.0,0.0,9.0

In [4]:
df['heure'] = df['heure'].str.slice(start=0, stop=2).astype(int)

In [5]:
df['isWeekday'] = df['isWeekday'].replace({False:0, True:1})
df['isHoliday'] = df['isHoliday'].replace({False:0, True:1})

In [6]:
df = pd.get_dummies(df, columns=['season'], drop_first=False)

In [7]:
df

,heure,year,month,day,Frequentation,isWeekday,isHoliday,RR1,QRR1,DRR1,...,GLO2,QGLO2,INS,QINS,INS2,QINS2,season_autumn,season_spring,season_summer,season_winter
0,0,2022,1,1,1469,0,1,0.0,1.0,0.0,...,0.0,9.0,0.0,9.0,0.0,9.0,False,False,False,True
1,1,2022,1,1,910,0,1,0.0,1.0,0.0,...,0.0,9.0,0.0,9.0,0.0,9.0,False,False,False,True
2,2,2022,1,1,535,0,1,0.0,1.0,0.0,...,0.0,9.0,0.0,9.0,0.0,9.0,False,False,False,True
3,3,2022,1,1,200,0,1,0.0,1.0,0.0,...,0.0,9.0,0.0,9.0,0.0,9.0,False,False,False,True
4,4,2022,1,1,406,0,1,0.0,1.0,0.0,...,0.0,9.0,0.0,9.0,0.0,9.0,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18303,19,2024,9,30,6291,1,0,0.0,1.0,0.0,...,0.0,9.0,0.0,9.0,0.0,9.0,True,False,False,False
18304,20,2024,9,30,7431,1,0,0.0,1.0,0.0,...,0.0,9.0,0.0,9.0,0.0,9.0,True,False,False,False
18305,21,2024,9,30,2081,1,0,0.0,1.0,0.0,...,0.0,9.0,0.0,9.0,0.0,9.0,True,False,False,False
18306,22,2024,9,30,2318,1,0,0.0,1.0,0.0,...,0.0,9.0,0.0,9.0,0.0,9.0,True,False,False,False
18307,23,2024,9,30,876,1,0,0.0,1.0,0.0,...,0.0,9.0,0.0,9.0,0.0,9.0,True,False,False,False

We take the train set and split it bewtween train and validation

In [8]:
X_train, y_train, X_valid, y_valid, X_test, y_test = train_valid_test_split(df, target='Frequentation', train_size=0.6, valid_size=0.2, test_size=0.2)

We initialize the benchmark storing list

In [9]:
benchmark = []

In [10]:
kf = KFold(n_splits=10,random_state=520,shuffle=True)

# Random Forest

In [11]:
from sklearn.ensemble import RandomForestRegressor

In [12]:
X_rf = X_valid.copy()
y_rf = y_valid.copy()

In [13]:
rf = RandomForestRegressor(random_state=520)

In [14]:
rf_scores = []

In [15]:
for i, (train_index, test_index) in enumerate(kf.split(X_rf)):

    X_rf_train, X_rf_test, y_rf_train, y_rf_test = X_rf.iloc[train_index], X_rf.iloc[test_index], y_rf.iloc[train_index], y_rf.iloc[test_index]

    rf.fit(X_rf_train, y_rf_train)
    preds = rf.predict(X_rf_test)

    rmse = root_mean_squared_error(y_rf_test, preds)

    print(f'iter {i} : {rmse}')

    rf_scores.append(rmse)

print('----- score moyen -----')
rf_score = np.mean(rf_scores, axis=0)
print(f'Random Forest : {rf_score}')

iter 0 : 1496.7060648087017
iter 1 : 1464.3838735887196
iter 2 : 1351.000511164585
iter 3 : 1572.0287450361539
iter 4 : 1450.3861379804696
iter 5 : 1604.3056797417505
iter 6 : 1420.0976296586168
iter 7 : 1270.8020657490379
iter 8 : 1498.6597273077364
iter 9 : 1233.1893489165188
----- score moyen -----
Random Forest : 1436.155978395229

In [16]:
benchmark.append(np.concatenate((np.array(['Random Forest']), [rf_score])))

# Regression multiple

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
X_reg = X_valid.copy()
y_reg = y_valid.copy()

In [19]:
X_reg = X_reg.fillna(0)

In [20]:
reg = LinearRegression()

In [21]:
reg_scores = []

In [22]:
for i, (train_index, test_index) in enumerate(kf.split(X_reg)):

    X_reg_train, X_reg_test, y_reg_train, y_reg_test = X_reg.iloc[train_index], X_reg.iloc[test_index], y_reg.iloc[train_index], y_reg.iloc[test_index]

    reg.fit(X_reg_train, y_reg_train)
    preds = reg.predict(X_reg_test)

    rmse = root_mean_squared_error(y_reg_test, preds)

    print(f'iter {i} : {rmse}')

    reg_scores.append(rmse)

print('----- score moyen -----')
reg_score = np.mean(reg_scores, axis=0)
print(f'Random Forest Regressor : {reg_score}')

iter 0 : 3882.476868278379
iter 1 : 3609.2242036813645
iter 2 : 3332.900646052733
iter 3 : 3166.0270346579105
iter 4 : 3255.9565704126735
iter 5 : 3582.3322201293413
iter 6 : 34379.180413855924
iter 7 : 3475.5392474781243
iter 8 : 4105.19740801899
iter 9 : 3533.3961462847537
----- score moyen -----
Random Forest Regressor : 6632.22307588502

In [23]:
benchmark.append(np.concatenate((np.array(['Multiple Regressor']), [reg_score])))

# Gradient Boosting Regressor

In [24]:
from sklearn.ensemble import HistGradientBoostingRegressor

In [25]:
X_gb = X_valid.copy()
y_gb = y_valid.copy()

In [26]:
gb = HistGradientBoostingRegressor(random_state=520)

In [27]:
gb_scores = []

In [28]:
for i, (train_index, test_index) in enumerate(kf.split(X_gb)):

    X_gb_train, X_gb_test, y_gb_train, y_gb_test = X_gb.iloc[train_index], X_gb.iloc[test_index], y_gb.iloc[train_index], y_gb.iloc[test_index]

    gb.fit(X_gb_train, y_gb_train)
    preds = gb.predict(X_gb_test)

    rmse = root_mean_squared_error(y_gb_test, preds)

    print(f'iter {i} : {rmse}')

    gb_scores.append(rmse)

print('----- score moyen -----')
gb_score = np.mean(gb_scores, axis=0)
print(f'Gradient Boosting : {gb_score}')

iter 0 : 1179.9365005248708
iter 1 : 1234.9173767321656
iter 2 : 1110.0881694574086
iter 3 : 1321.4515964739242
iter 4 : 1256.5955496134516
iter 5 : 1307.6171855783498
iter 6 : 1175.8786387916841
iter 7 : 1016.7082699312116
iter 8 : 1290.4714998717893
iter 9 : 1131.495320088777
----- score moyen -----
Gradient Boosting : 1202.5160107063634

In [29]:
benchmark.append(np.concatenate((np.array(['Gradient Boosting']), [gb_score])))

# AdaBoost Regressor

In [30]:
from sklearn.ensemble import AdaBoostRegressor

In [31]:
X_ab = X_valid.copy()
y_ab = y_valid.copy()

In [32]:
X_ab= X_ab.fillna(0)

In [33]:
ab = AdaBoostRegressor(random_state=520)

In [34]:
ab_scores = []

In [35]:
for i, (train_index, test_index) in enumerate(kf.split(X_ab)):

    X_ab_train, X_ab_test, y_ab_train, y_ab_test = X_ab.iloc[train_index], X_ab.iloc[test_index], y_ab.iloc[train_index], y_ab.iloc[test_index]

    ab.fit(X_ab_train, y_ab_train)
    preds = ab.predict(X_ab_test)

    rmse = root_mean_squared_error(y_ab_test, preds)

    print(f'iter {i} : {rmse}')

    ab_scores.append(rmse)

print('----- score moyen -----')
ab_score = np.mean(ab_scores, axis=0)
print(f'AdaBoost : {ab_score}')

iter 0 : 2571.94085111079
iter 1 : 2788.7643156197055
iter 2 : 2698.5039310857996
iter 3 : 2353.835831264178
iter 4 : 2560.052703249861
iter 5 : 2569.3807169407523
iter 6 : 2378.7630582959628
iter 7 : 2493.1409079011437
iter 8 : 2714.4270696436397
iter 9 : 2627.5605352356943
----- score moyen -----
AdaBoost : 2575.6369920347524

In [36]:
benchmark.append(np.concatenate((np.array(['AdaBoost']), [ab_score])))

# Results

We create the benchmark dataframe

In [37]:
bench_df = pd.DataFrame(benchmark, columns=['Model', 'RMSE'])

In [38]:
bench_df

                Model                RMSE
0       Random Forest   1436.155978395229
1  Multiple Regressor    6632.22307588502
2   Gradient Boosting  1202.5160107063634
3            AdaBoost  2575.6369920347524